export interface Airport {
  iata: string;
  name: string;
  city: string;
  country: string;
}

export const AIRPORTS: Airport[] = [
  // Deutschland
  { iata: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt', country: 'Deutschland' },
  { iata: 'MUC', name: 'München Airport', city: 'München', country: 'Deutschland' },
  { iata: 'BER', name: 'Berlin Brandenburg', city: 'Berlin', country: 'Deutschland' },
  { iata: 'HAM', name: 'Hamburg Airport', city: 'Hamburg', country: 'Deutschland' },
  { iata: 'DUS', name: 'Düsseldorf Airport', city: 'Düsseldorf', country: 'Deutschland' },
  { iata: 'CGN', name: 'Köln Bonn Airport', city: 'Köln', country: 'Deutschland' },
  { iata: 'STR', name: 'Stuttgart Airport', city: 'Stuttgart', country: 'Deutschland' },
  { iata: 'NUE', name: 'Nürnberg Airport', city: 'Nürnberg', country: 'Deutschland' },
  { iata: 'HAJ', name: 'Hannover Airport', city: 'Hannover', country: 'Deutschland' },
  { iata: 'LEJ', name: 'Leipzig Halle', city: 'Leipzig', country: 'Deutschland' },
  { iata: 'BRE', name: 'Bremen Airport', city: 'Bremen', country: 'Deutschland' },
  { iata: 'DRS', name: 'Dresden Airport', city: 'Dresden', country: 'Deutschland' },
  { iata: 'DTM', name: 'Dortmund Airport', city: 'Dortmund', country: 'Deutschland' },
  { iata: 'FMM', name: 'Memmingen Airport', city: 'Memmingen', country: 'Deutschland' },
  { iata: 'KSF', name: 'Kassel Calden', city: 'Kassel', country: 'Deutschland' },
  { iata: 'FDH', name: 'Friedrichshafen Airport', city: 'Friedrichshafen', country: 'Deutschland' },
  { iata: 'PAD', name: 'Paderborn Lippstadt', city: 'Paderborn', country: 'Deutschland' },
  { iata: 'BWE', name: 'Braunschweig Wolfsburg', city: 'Braunschweig', country: 'Deutschland' },
  // Schweiz
  { iata: 'ZRH', name: 'Zürich Airport', city: 'Zürich', country: 'Schweiz' },
  { iata: 'GVA', name: 'Genève Airport', city: 'Genf', country: 'Schweiz' },
  { iata: 'BSL', name: 'EuroAirport Basel', city: 'Basel', country: 'Schweiz' },
  { iata: 'BRN', name: 'Bern Airport', city: 'Bern', country: 'Schweiz' },
  { iata: 'LUG', name: 'Lugano Airport', city: 'Lugano', country: 'Schweiz' },
  { iata: 'SIR', name: 'Sion Airport', city: 'Sion', country: 'Schweiz' },
  // Österreich
  { iata: 'VIE', name: 'Wien Schwechat', city: 'Wien', country: 'Österreich' },
  { iata: 'SZG', name: 'Salzburg Airport', city: 'Salzburg', country: 'Österreich' },
  { iata: 'INN', name: 'Innsbruck Airport', city: 'Innsbruck', country: 'Österreich' },
  { iata: 'GRZ', name: 'Graz Airport', city: 'Graz', country: 'Österreich' },
  { iata: 'LNZ', name: 'Linz Airport', city: 'Linz', country: 'Österreich' },
  { iata: 'KLU', name: 'Klagenfurt Airport', city: 'Klagenfurt', country: 'Österreich' },
  // Großbritannien & Irland
  { iata: 'LHR', name: 'London Heathrow', city: 'London', country: 'Großbritannien' },
  { iata: 'LGW', name: 'London Gatwick', city: 'London', country: 'Großbritannien' },
  { iata: 'MAN', name: 'Manchester Airport', city: 'Manchester', country: 'Großbritannien' },
  { iata: 'STN', name: 'London Stansted', city: 'London', country: 'Großbritannien' },
  { iata: 'LTN', name: 'London Luton', city: 'London', country: 'Großbritannien' },
  { iata: 'BHX', name: 'Birmingham Airport', city: 'Birmingham', country: 'Großbritannien' },
  { iata: 'EDI', name: 'Edinburgh Airport', city: 'Edinburgh', country: 'Großbritannien' },
  { iata: 'GLA', name: 'Glasgow Airport', city: 'Glasgow', country: 'Großbritannien' },
  { iata: 'BRS', name: 'Bristol Airport', city: 'Bristol', country: 'Großbritannien' },
  { iata: 'NCL', name: 'Newcastle Airport', city: 'Newcastle', country: 'Großbritannien' },
  { iata: 'LPL', name: 'Liverpool Airport', city: 'Liverpool', country: 'Großbritannien' },
  { iata: 'ABZ', name: 'Aberdeen Airport', city: 'Aberdeen', country: 'Großbritannien' },
  { iata: 'BFS', name: 'Belfast International', city: 'Belfast', country: 'Großbritannien' },
  { iata: 'CWL', name: 'Cardiff Airport', city: 'Cardiff', country: 'Großbritannien' },
  { iata: 'EMA', name: 'East Midlands Airport', city: 'Nottingham', country: 'Großbritannien' },
  { iata: 'LBA', name: 'Leeds Bradford', city: 'Leeds', country: 'Großbritannien' },
  { iata: 'SOU', name: 'Southampton Airport', city: 'Southampton', country: 'Großbritannien' },
  { iata: 'INV', name: 'Inverness Airport', city: 'Inverness', country: 'Großbritannien' },
  { iata: 'DUB', name: 'Dublin Airport', city: 'Dublin', country: 'Irland' },
  { iata: 'ORK', name: 'Cork Airport', city: 'Cork', country: 'Irland' },
  { iata: 'SNN', name: 'Shannon Airport', city: 'Shannon', country: 'Irland' },
  // Frankreich
  { iata: 'CDG', name: 'Paris Charles de Gaulle', city: 'Paris', country: 'Frankreich' },
  { iata: 'ORY', name: 'Paris Orly', city: 'Paris', country: 'Frankreich' },
  { iata: 'NCE', name: 'Nizza Côte d\'Azur', city: 'Nizza', country: 'Frankreich' },
  { iata: 'LYS', name: 'Lyon Saint-Exupéry', city: 'Lyon', country: 'Frankreich' },
  { iata: 'MRS', name: 'Marseille Provence', city: 'Marseille', country: 'Frankreich' },
  { iata: 'BOD', name: 'Bordeaux Mérignac', city: 'Bordeaux', country: 'Frankreich' },
  { iata: 'TLS', name: 'Toulouse Blagnac', city: 'Toulouse', country: 'Frankreich' },
  { iata: 'NTE', name: 'Nantes Airport', city: 'Nantes', country: 'Frankreich' },
  { iata: 'BIA', name: 'Bastia Airport', city: 'Bastia', country: 'Frankreich' },
  { iata: 'AJA', name: 'Ajaccio Airport', city: 'Ajaccio', country: 'Frankreich' },
  { iata: 'BES', name: 'Brest Airport', city: 'Brest', country: 'Frankreich' },
  { iata: 'MPL', name: 'Montpellier Airport', city: 'Montpellier', country: 'Frankreich' },
  { iata: 'SXB', name: 'Straßburg Airport', city: 'Straßburg', country: 'Frankreich' },
  // Spanien & Portugal
  { iata: 'MAD', name: 'Madrid Barajas', city: 'Madrid', country: 'Spanien' },
  { iata: 'BCN', name: 'Barcelona El Prat', city: 'Barcelona', country: 'Spanien' },
  { iata: 'PMI', name: 'Palma de Mallorca', city: 'Palma', country: 'Spanien' },
  { iata: 'AGP', name: 'Málaga Airport', city: 'Málaga', country: 'Spanien' },
  { iata: 'ALC', name: 'Alicante Airport', city: 'Alicante', country: 'Spanien' },
  { iata: 'VLC', name: 'Valencia Airport', city: 'Valencia', country: 'Spanien' },
  { iata: 'SVQ', name: 'Sevilla Airport', city: 'Sevilla', country: 'Spanien' },
  { iata: 'BIO', name: 'Bilbao Airport', city: 'Bilbao', country: 'Spanien' },
  { iata: 'OVD', name: 'Oviedo Airport', city: 'Oviedo', country: 'Spanien' },
  { iata: 'SCQ', name: 'Santiago de Compostela', city: 'Santiago', country: 'Spanien' },
  { iata: 'LPA', name: 'Las Palmas Airport', city: 'Las Palmas', country: 'Spanien' },
  { iata: 'TFS', name: 'Tenerife Süd', city: 'Teneriffa', country: 'Spanien' },
  { iata: 'TFN', name: 'Tenerife Nord', city: 'Teneriffa', country: 'Spanien' },
  { iata: 'IBZ', name: 'Ibiza Airport', city: 'Ibiza', country: 'Spanien' },
  { iata: 'MAH', name: 'Menorca Airport', city: 'Menorca', country: 'Spanien' },
  { iata: 'FUE', name: 'Fuerteventura Airport', city: 'Fuerteventura', country: 'Spanien' },
  { iata: 'LIS', name: 'Lissabon Humberto Delgado', city: 'Lissabon', country: 'Portugal' },
  { iata: 'OPO', name: 'Porto Airport', city: 'Porto', country: 'Portugal' },
  { iata: 'FAO', name: 'Faro Airport', city: 'Faro', country: 'Portugal' },
  { iata: 'FNC', name: 'Funchal Airport', city: 'Funchal', country: 'Portugal' },
  // Italien
  { iata: 'FCO', name: 'Rom Fiumicino', city: 'Rom', country: 'Italien' },
  { iata: 'MXP', name: 'Milano Malpensa', city: 'Mailand', country: 'Italien' },
  { iata: 'LIN', name: 'Milano Linate', city: 'Mailand', country: 'Italien' },
  { iata: 'BGY', name: 'Bergamo Orio al Serio', city: 'Bergamo', country: 'Italien' },
  { iata: 'CIA', name: 'Rom Ciampino', city: 'Rom', country: 'Italien' },
  { iata: 'VCE', name: 'Venedig Marco Polo', city: 'Venedig', country: 'Italien' },
  { iata: 'NAP', name: 'Neapel Capodichino', city: 'Neapel', country: 'Italien' },
  { iata: 'FLR', name: 'Florenz Peretola', city: 'Florenz', country: 'Italien' },
  { iata: 'TRN', name: 'Turin Airport', city: 'Turin', country: 'Italien' },
  { iata: 'BLQ', name: 'Bologna Airport', city: 'Bologna', country: 'Italien' },
  { iata: 'CTA', name: 'Catania Fontanarossa', city: 'Catania', country: 'Italien' },
  { iata: 'PMO', name: 'Palermo Airport', city: 'Palermo', country: 'Italien' },
  { iata: 'CAG', name: 'Cagliari Airport', city: 'Cagliari', country: 'Italien' },
  { iata: 'GOA', name: 'Genua Airport', city: 'Genua', country: 'Italien' },
  { iata: 'BRI', name: 'Bari Airport', city: 'Bari', country: 'Italien' },
  { iata: 'PSA', name: 'Pisa Airport', city: 'Pisa', country: 'Italien' },
  // Niederlande, Belgien & Luxemburg
  { iata: 'AMS', name: 'Amsterdam Schiphol', city: 'Amsterdam', country: 'Niederlande' },
  { iata: 'EIN', name: 'Eindhoven Airport', city: 'Eindhoven', country: 'Niederlande' },
  { iata: 'RTM', name: 'Rotterdam Airport', city: 'Rotterdam', country: 'Niederlande' },
  { iata: 'BRU', name: 'Brüssel Airport', city: 'Brüssel', country: 'Belgien' },
  { iata: 'CRL', name: 'Charleroi Airport', city: 'Charleroi', country: 'Belgien' },
  { iata: 'ANR', name: 'Antwerpen Airport', city: 'Antwerpen', country: 'Belgien' },
  { iata: 'LUX', name: 'Luxemburg Airport', city: 'Luxemburg', country: 'Luxemburg' },
  // Skandinavien & Nordische Länder
  { iata: 'CPH', name: 'Kopenhagen Kastrup', city: 'Kopenhagen', country: 'Dänemark' },
  { iata: 'BLL', name: 'Billund Airport', city: 'Billund', country: 'Dänemark' },
  { iata: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm', country: 'Schweden' },
  { iata: 'GOT', name: 'Göteborg Landvetter', city: 'Göteborg', country: 'Schweden' },
  { iata: 'MMX', name: 'Malmö Airport', city: 'Malmö', country: 'Schweden' },
  { iata: 'OSL', name: 'Oslo Gardermoen', city: 'Oslo', country: 'Norwegen' },
  { iata: 'BGO', name: 'Bergen Airport', city: 'Bergen', country: 'Norwegen' },
  { iata: 'TRD', name: 'Trondheim Airport', city: 'Trondheim', country: 'Norwegen' },
  { iata: 'SVG', name: 'Stavanger Airport', city: 'Stavanger', country: 'Norwegen' },
  { iata: 'KEF', name: 'Keflavík International', city: 'Reykjavík', country: 'Island' },
  { iata: 'HEL', name: 'Helsinki Vantaa', city: 'Helsinki', country: 'Finnland' },
  { iata: 'TMP', name: 'Tampere Airport', city: 'Tampere', country: 'Finnland' },
  { iata: 'TKU', name: 'Turku Airport', city: 'Turku', country: 'Finnland' },
  { iata: 'RIX', name: 'Riga Airport', city: 'Riga', country: 'Lettland' },
  { iata: 'TLL', name: 'Tallinn Airport', city: 'Tallinn', country: 'Estland' },
  { iata: 'VNO', name: 'Vilnius Airport', city: 'Vilnius', country: 'Litauen' },
  { iata: 'KUN', name: 'Kaunas Airport', city: 'Kaunas', country: 'Litauen' },
  // Osteuropa
  { iata: 'WAW', name: 'Warschau Chopin', city: 'Warschau', country: 'Polen' },
  { iata: 'KRK', name: 'Krakau Airport', city: 'Krakau', country: 'Polen' },
  { iata: 'GDN', name: 'Danzig Airport', city: 'Danzig', country: 'Polen' },
  { iata: 'WRO', name: 'Breslau Airport', city: 'Breslau', country: 'Polen' },
  { iata: 'KTW', name: 'Kattowitz Airport', city: 'Kattowitz', country: 'Polen' },
  { iata: 'PRG', name: 'Prag Ruzyně', city: 'Prag', country: 'Tschechien' },
  { iata: 'BTS', name: 'Bratislava Airport', city: 'Bratislava', country: 'Slowakei' },
  { iata: 'BUD', name: 'Budapest Liszt Ferenc', city: 'Budapest', country: 'Ungarn' },
  { iata: 'OTP', name: 'Bukarest Otopeni', city: 'Bukarest', country: 'Rumänien' },
  { iata: 'CLJ', name: 'Klausenburg Airport', city: 'Klausenburg', country: 'Rumänien' },
  { iata: 'SOF', name: 'Sofia Airport', city: 'Sofia', country: 'Bulgarien' },
  { iata: 'VAR', name: 'Warna Airport', city: 'Warna', country: 'Bulgarien' },
  { iata: 'ZAG', name: 'Zagreb Airport', city: 'Zagreb', country: 'Kroatien' },
  { iata: 'SPU', name: 'Split Airport', city: 'Split', country: 'Kroatien' },
  { iata: 'DBV', name: 'Dubrovnik Airport', city: 'Dubrovnik', country: 'Kroatien' },
  { iata: 'SJJ', name: 'Sarajevo Airport', city: 'Sarajevo', country: 'Bosnien und Herzegowina' },
  { iata: 'BEG', name: 'Belgrad Nikola Tesla', city: 'Belgrad', country: 'Serbien' },
  { iata: 'TGD', name: 'Podgorica Airport', city: 'Podgorica', country: 'Montenegro' },
  { iata: 'TIA', name: 'Tirana Airport', city: 'Tirana', country: 'Albanien' },
  { iata: 'SKP', name: 'Skopje Airport', city: 'Skopje', country: 'Nordmazedonien' },
  { iata: 'LJU', name: 'Ljubljana Airport', city: 'Ljubljana', country: 'Slowenien' },
  { iata: 'KIV', name: 'Chișinău Airport', city: 'Chișinău', country: 'Moldau' },
  // Griechenland, Türkei & Zypern
  { iata: 'ATH', name: 'Athen Eleftherios Venizelos', city: 'Athen', country: 'Griechenland' },
  { iata: 'SKG', name: 'Thessaloniki Airport', city: 'Thessaloniki', country: 'Griechenland' },
  { iata: 'HER', name: 'Heraklion Airport', city: 'Heraklion', country: 'Griechenland' },
  { iata: 'RHO', name: 'Rhodos Airport', city: 'Rhodos', country: 'Griechenland' },
  { iata: 'CHQ', name: 'Chania Airport', city: 'Chania', country: 'Griechenland' },
  { iata: 'KLX', name: 'Kalamata Airport', city: 'Kalamata', country: 'Griechenland' },
  { iata: 'IST', name: 'Istanbul Airport', city: 'Istanbul', country: 'Türkei' },
  { iata: 'SAW', name: 'Istanbul Sabiha Gökçen', city: 'Istanbul', country: 'Türkei' },
  { iata: 'AYT', name: 'Antalya Airport', city: 'Antalya', country: 'Türkei' },
  { iata: 'ESB', name: 'Ankara Esenboğa', city: 'Ankara', country: 'Türkei' },
  { iata: 'DLM', name: 'Dalaman Airport', city: 'Dalaman', country: 'Türkei' },
  { iata: 'ADB', name: 'Izmir Airport', city: 'Izmir', country: 'Türkei' },
  { iata: 'LCA', name: 'Larnaca Airport', city: 'Larnaca', country: 'Zypern' },
  { iata: 'PFO', name: 'Paphos Airport', city: 'Paphos', country: 'Zypern' },
  // Russland, Ukraine & Belarus
  { iata: 'SVO', name: 'Moskau Sheremetyevo', city: 'Moskau', country: 'Russland' },
  { iata: 'DME', name: 'Moskau Domodedovo', city: 'Moskau', country: 'Russland' },
  { iata: 'VKO', name: 'Moskau Vnukovo', city: 'Moskau', country: 'Russland' },
  { iata: 'LED', name: 'St. Petersburg Pulkovo', city: 'St. Petersburg', country: 'Russland' },
  { iata: 'KZN', name: 'Kasan Airport', city: 'Kasan', country: 'Russland' },
  { iata: 'AER', name: 'Sotschi Airport', city: 'Sotschi', country: 'Russland' },
  { iata: 'KBP', name: 'Kiew Boryspil', city: 'Kiew', country: 'Ukraine' },
  { iata: 'IEV', name: 'Kiew Zhuliany', city: 'Kiew', country: 'Ukraine' },
  { iata: 'MSQ', name: 'Minsk Airport', city: 'Minsk', country: 'Belarus' },
  // Naher Osten
  { iata: 'DXB', name: 'Dubai International', city: 'Dubai', country: 'VAE' },
  { iata: 'DWC', name: 'Dubai World Central', city: 'Dubai', country: 'VAE' },
  { iata: 'AUH', name: 'Abu Dhabi International', city: 'Abu Dhabi', country: 'VAE' },
  { iata: 'SHJ', name: 'Sharjah Airport', city: 'Sharjah', country: 'VAE' },
  { iata: 'DOH', name: 'Hamad International', city: 'Doha', country: 'Katar' },
  { iata: 'RUH', name: 'Riad King Khalid', city: 'Riad', country: 'Saudi-Arabien' },
  { iata: 'JED', name: 'Dschidda King Abdulaziz', city: 'Dschidda', country: 'Saudi-Arabien' },
  { iata: 'MED', name: 'Medina Airport', city: 'Medina', country: 'Saudi-Arabien' },
  { iata: 'DMM', name: 'Dammam Airport', city: 'Dammam', country: 'Saudi-Arabien' },
  { iata: 'AMM', name: 'Amman Queen Alia', city: 'Amman', country: 'Jordanien' },
  { iata: 'BEY', name: 'Beirut Airport', city: 'Beirut', country: 'Libanon' },
  { iata: 'DAM', name: 'Damaskus Airport', city: 'Damaskus', country: 'Syrien' },
  { iata: 'TLV', name: 'Tel Aviv Ben Gurion', city: 'Tel Aviv', country: 'Israel' },
  { iata: 'KWI', name: 'Kuwait Airport', city: 'Kuwait', country: 'Kuwait' },
  { iata: 'BAH', name: 'Bahrain Airport', city: 'Manama', country: 'Bahrain' },
  { iata: 'MCT', name: 'Muscat Airport', city: 'Muscat', country: 'Oman' },
  { iata: 'BGW', name: 'Bagdad Airport', city: 'Bagdad', country: 'Irak' },
  { iata: 'IKA', name: 'Teheran Imam Khomeini', city: 'Teheran', country: 'Iran' },
  // Afrika
  { iata: 'ADD', name: 'Addis Ababa Bole International', city: 'Addis Abeba', country: 'Äthiopien' },
  { iata: 'WDH', name: 'Hosea Kutako International', city: 'Windhoek', country: 'Namibia' },
  { iata: 'WVB', name: 'Walvis Bay Airport', city: 'Walvis Bay', country: 'Namibia' },
  { iata: 'JNB', name: 'O.R. Tambo International', city: 'Johannesburg', country: 'Südafrika' },
  { iata: 'CPT', name: 'Cape Town International', city: 'Kapstadt', country: 'Südafrika' },
  { iata: 'DUR', name: 'Durban King Shaka', city: 'Durban', country: 'Südafrika' },
  { iata: 'CAI', name: 'Kairo International', city: 'Kairo', country: 'Ägypten' },
  { iata: 'HRG', name: 'Hurghada Airport', city: 'Hurghada', country: 'Ägypten' },
  { iata: 'SSH', name: 'Sharm El-Sheikh', city: 'Sharm El-Sheikh', country: 'Ägypten' },
  { iata: 'LXR', name: 'Luxor Airport', city: 'Luxor', country: 'Ägypten' },
  { iata: 'NBO', name: 'Nairobi Jomo Kenyatta', city: 'Nairobi', country: 'Kenia' },
  { iata: 'MBA', name: 'Mombasa Airport', city: 'Mombasa', country: 'Kenia' },
  { iata: 'ACC', name: 'Accra Kotoka', city: 'Accra', country: 'Ghana' },
  { iata: 'LOS', name: 'Lagos Murtala Muhammed', city: 'Lagos', country: 'Nigeria' },
  { iata: 'ABV', name: 'Abuja Airport', city: 'Abuja', country: 'Nigeria' },
  { iata: 'CMN', name: 'Casablanca Mohammed V', city: 'Casablanca', country: 'Marokko' },
  { iata: 'RAK', name: 'Marrakesch Airport', city: 'Marrakesch', country: 'Marokko' },
  { iata: 'AGA', name: 'Agadir Airport', city: 'Agadir', country: 'Marokko' },
  { iata: 'TUN', name: 'Tunis Airport', city: 'Tunis', country: 'Tunesien' },
  { iata: 'DJE', name: 'Djerba Airport', city: 'Djerba', country: 'Tunesien' },
  { iata: 'ALG', name: 'Algier Airport', city: 'Algier', country: 'Algerien' },
  { iata: 'DAR', name: 'Daressalam Airport', city: 'Daressalam', country: 'Tansania' },
  { iata: 'JRO', name: 'Kilimanjaro Airport', city: 'Kilimanjaro', country: 'Tansania' },
  { iata: 'ZNZ', name: 'Sansibar Airport', city: 'Sansibar', country: 'Tansania' },
  { iata: 'KGL', name: 'Kigali Airport', city: 'Kigali', country: 'Ruanda' },
  { iata: 'FIH', name: 'Kinshasa Airport', city: 'Kinshasa', country: 'DR Kongo' },
  { iata: 'FBM', name: 'Lubumbashi Airport', city: 'Lubumbashi', country: 'DR Kongo' },
  { iata: 'DLA', name: 'Douala Airport', city: 'Douala', country: 'Kamerun' },
  { iata: 'MPM', name: 'Maputo Airport', city: 'Maputo', country: 'Mosambik' },
  { iata: 'LUN', name: 'Lusaka Airport', city: 'Lusaka', country: 'Sambia' },
  { iata: 'HRE', name: 'Harare Airport', city: 'Harare', country: 'Simbabwe' },
  { iata: 'DKR', name: 'Dakar Airport', city: 'Dakar', country: 'Senegal' },
  { iata: 'ABJ', name: 'Abidjan Airport', city: 'Abidjan', country: 'Elfenbeinküste' },
  { iata: 'MGQ', name: 'Mogadischu Airport', city: 'Mogadischu', country: 'Somalia' },
  { iata: 'KRT', name: 'Khartum Airport', city: 'Khartum', country: 'Sudan' },
  { iata: 'TNR', name: 'Antananarivo Airport', city: 'Antananarivo', country: 'Madagaskar' },
  { iata: 'MRU', name: 'Mauritius Airport', city: 'Mauritius', country: 'Mauritius' },
  { iata: 'RUN', name: 'Réunion Airport', city: 'Saint-Denis', country: 'Réunion' },
  { iata: 'SEZ', name: 'Seychellen Airport', city: 'Victoria', country: 'Seychellen' },
  // China & Ostasien
  { iata: 'PEK', name: 'Peking Capital', city: 'Peking', country: 'China' },
  { iata: 'PKX', name: 'Peking Daxing', city: 'Peking', country: 'China' },
  { iata: 'PVG', name: 'Shanghai Pudong', city: 'Shanghai', country: 'China' },
  { iata: 'SHA', name: 'Shanghai Hongqiao', city: 'Shanghai', country: 'China' },
  { iata: 'CAN', name: 'Guangzhou Baiyun', city: 'Guangzhou', country: 'China' },
  { iata: 'SZX', name: 'Shenzhen Airport', city: 'Shenzhen', country: 'China' },
  { iata: 'CTU', name: 'Chengdu Airport', city: 'Chengdu', country: 'China' },
  { iata: 'XIY', name: 'Xi\'an Xianyang', city: 'Xi\'an', country: 'China' },
  { iata: 'KMG', name: 'Kunming Airport', city: 'Kunming', country: 'China' },
  { iata: 'HGH', name: 'Hangzhou Airport', city: 'Hangzhou', country: 'China' },
  { iata: 'NKG', name: 'Nanjing Airport', city: 'Nanjing', country: 'China' },
  { iata: 'WUH', name: 'Wuhan Airport', city: 'Wuhan', country: 'China' },
  { iata: 'XMN', name: 'Xiamen Airport', city: 'Xiamen', country: 'China' },
  { iata: 'TAO', name: 'Qingdao Airport', city: 'Qingdao', country: 'China' },
  { iata: 'CKG', name: 'Chongqing Airport', city: 'Chongqing', country: 'China' },
  { iata: 'KWE', name: 'Guiyang Airport', city: 'Guiyang', country: 'China' },
  { iata: 'URC', name: 'Urumqi Airport', city: 'Urumqi', country: 'China' },
  { iata: 'SHE', name: 'Shenyang Airport', city: 'Shenyang', country: 'China' },
  { iata: 'TSN', name: 'Tianjin Airport', city: 'Tianjin', country: 'China' },
  { iata: 'HRB', name: 'Harbin Airport', city: 'Harbin', country: 'China' },
  { iata: 'HKG', name: 'Hong Kong International', city: 'Hongkong', country: 'Hongkong' },
  { iata: 'MFM', name: 'Macau Airport', city: 'Macao', country: 'Macao' },
  { iata: 'TPE', name: 'Taipeh Taoyuan', city: 'Taipeh', country: 'Taiwan' },
  { iata: 'TSA', name: 'Taipeh Songshan', city: 'Taipeh', country: 'Taiwan' },
  { iata: 'KHH', name: 'Kaohsiung Airport', city: 'Kaohsiung', country: 'Taiwan' },
  // Japan & Südkorea
  { iata: 'NRT', name: 'Tokio Narita', city: 'Tokio', country: 'Japan' },
  { iata: 'HND', name: 'Tokio Haneda', city: 'Tokio', country: 'Japan' },
  { iata: 'KIX', name: 'Osaka Kansai', city: 'Osaka', country: 'Japan' },
  { iata: 'ITM', name: 'Osaka Itami', city: 'Osaka', country: 'Japan' },
  { iata: 'NGO', name: 'Nagoya Chubu', city: 'Nagoya', country: 'Japan' },
  { iata: 'CTS', name: 'Sapporo New Chitose', city: 'Sapporo', country: 'Japan' },
  { iata: 'FUK', name: 'Fukuoka Airport', city: 'Fukuoka', country: 'Japan' },
  { iata: 'OKA', name: 'Okinawa Naha', city: 'Okinawa', country: 'Japan' },
  { iata: 'SDJ', name: 'Sendai Airport', city: 'Sendai', country: 'Japan' },
  { iata: 'ICN', name: 'Seoul Incheon International', city: 'Seoul', country: 'Südkorea' },
  { iata: 'GMP', name: 'Seoul Gimpo', city: 'Seoul', country: 'Südkorea' },
  { iata: 'PUS', name: 'Busan Airport', city: 'Busan', country: 'Südkorea' },
  { iata: 'CJU', name: 'Jeju Airport', city: 'Jeju', country: 'Südkorea' },
  // Südostasien
  { iata: 'SIN', name: 'Singapore Changi', city: 'Singapur', country: 'Singapur' },
  { iata: 'BKK', name: 'Bangkok Suvarnabhumi', city: 'Bangkok', country: 'Thailand' },
  { iata: 'DMK', name: 'Bangkok Don Mueang', city: 'Bangkok', country: 'Thailand' },
  { iata: 'HKT', name: 'Phuket Airport', city: 'Phuket', country: 'Thailand' },
  { iata: 'CNX', name: 'Chiang Mai Airport', city: 'Chiang Mai', country: 'Thailand' },
  { iata: 'KUL', name: 'Kuala Lumpur International', city: 'Kuala Lumpur', country: 'Malaysia' },
  { iata: 'PEN', name: 'Penang Airport', city: 'Penang', country: 'Malaysia' },
  { iata: 'BKI', name: 'Kota Kinabalu', city: 'Kota Kinabalu', country: 'Malaysia' },
  { iata: 'MNL', name: 'Manila Ninoy Aquino', city: 'Manila', country: 'Philippinen' },
  { iata: 'CEB', name: 'Cebu Mactan', city: 'Cebu', country: 'Philippinen' },
  { iata: 'CGK', name: 'Jakarta Soekarno-Hatta', city: 'Jakarta', country: 'Indonesien' },
  { iata: 'DPS', name: 'Denpasar Bali', city: 'Denpasar', country: 'Indonesien' },
  { iata: 'SUB', name: 'Surabaya Airport', city: 'Surabaya', country: 'Indonesien' },
  { iata: 'SGN', name: 'Ho-Chi-Minh-Stadt Tan Son Nhat', city: 'Ho-Chi-Minh-Stadt', country: 'Vietnam' },
  { iata: 'HAN', name: 'Hanoi Noi Bai', city: 'Hanoi', country: 'Vietnam' },
  { iata: 'DAD', name: 'Da Nang Airport', city: 'Da Nang', country: 'Vietnam' },
  { iata: 'PNH', name: 'Phnom Penh Airport', city: 'Phnom Penh', country: 'Kambodscha' },
  { iata: 'REP', name: 'Siem Reap Airport', city: 'Siem Reap', country: 'Kambodscha' },
  { iata: 'VTE', name: 'Vientiane Airport', city: 'Vientiane', country: 'Laos' },
  { iata: 'RGN', name: 'Rangun Airport', city: 'Rangun', country: 'Myanmar' },
  { iata: 'BWN', name: 'Brunei Airport', city: 'Bandar Seri Begawan', country: 'Brunei' },
  { iata: 'DIL', name: 'Dili Airport', city: 'Dili', country: 'Osttimor' },
  // Indien & Südasien
  { iata: 'DEL', name: 'Delhi Indira Gandhi', city: 'Delhi', country: 'Indien' },
  { iata: 'BOM', name: 'Mumbai Chhatrapati Shivaji', city: 'Mumbai', country: 'Indien' },
  { iata: 'MAA', name: 'Chennai Airport', city: 'Chennai', country: 'Indien' },
  { iata: 'BLR', name: 'Bangalore Kempegowda', city: 'Bangalore', country: 'Indien' },
  { iata: 'HYD', name: 'Hyderabad Airport', city: 'Hyderabad', country: 'Indien' },
  { iata: 'CCU', name: 'Kolkata Netaji Subhas Chandra', city: 'Kolkata', country: 'Indien' },
  { iata: 'AMD', name: 'Ahmedabad Airport', city: 'Ahmedabad', country: 'Indien' },
  { iata: 'GOI', name: 'Goa Dabolim', city: 'Goa', country: 'Indien' },
  { iata: 'COK', name: 'Kochi Airport', city: 'Kochi', country: 'Indien' },
  { iata: 'JAI', name: 'Jaipur Airport', city: 'Jaipur', country: 'Indien' },
  { iata: 'PNQ', name: 'Pune Airport', city: 'Pune', country: 'Indien' },
  { iata: 'GAU', name: 'Guwahati Airport', city: 'Guwahati', country: 'Indien' },
  { iata: 'TRV', name: 'Thiruvananthapuram', city: 'Thiruvananthapuram', country: 'Indien' },
  { iata: 'IXC', name: 'Chandigarh Airport', city: 'Chandigarh', country: 'Indien' },
  { iata: 'LKO', name: 'Lucknow Airport', city: 'Lucknow', country: 'Indien' },
  { iata: 'KHI', name: 'Karachi Jinnah', city: 'Karachi', country: 'Pakistan' },
  { iata: 'LHE', name: 'Lahore Airport', city: 'Lahore', country: 'Pakistan' },
  { iata: 'ISB', name: 'Islamabad Airport', city: 'Islamabad', country: 'Pakistan' },
  { iata: 'CMB', name: 'Colombo Bandaranaike', city: 'Colombo', country: 'Sri Lanka' },
  { iata: 'DAC', name: 'Dhaka Hazrat Shahjalal', city: 'Dhaka', country: 'Bangladesch' },
  { iata: 'KTM', name: 'Kathmandu Tribhuvan', city: 'Kathmandu', country: 'Nepal' },
  { iata: 'MLE', name: 'Malé Airport', city: 'Malé', country: 'Malediven' },
  // Zentralasien & Kaukasus
  { iata: 'ALA', name: 'Almaty Airport', city: 'Almaty', country: 'Kasachstan' },
  { iata: 'NQZ', name: 'Astana Airport', city: 'Astana', country: 'Kasachstan' },
  { iata: 'TAS', name: 'Taschkent Airport', city: 'Taschkent', country: 'Usbekistan' },
  { iata: 'EVN', name: 'Eriwan Swartnoz', city: 'Eriwan', country: 'Armenien' },
  { iata: 'TBS', name: 'Tiflis Airport', city: 'Tiflis', country: 'Georgien' },
  { iata: 'GYD', name: 'Baku Heydar Aliyev', city: 'Baku', country: 'Aserbaidschan' },
  // USA - Große Drehkreuze
  { iata: 'JFK', name: 'New York John F. Kennedy', city: 'New York', country: 'USA' },
  { iata: 'EWR', name: 'Newark Liberty', city: 'New York', country: 'USA' },
  { iata: 'LGA', name: 'New York LaGuardia', city: 'New York', country: 'USA' },
  { iata: 'LAX', name: 'Los Angeles International', city: 'Los Angeles', country: 'USA' },
  { iata: 'SFO', name: 'San Francisco International', city: 'San Francisco', country: 'USA' },
  { iata: 'ORD', name: 'Chicago O\'Hare', city: 'Chicago', country: 'USA' },
  { iata: 'MDW', name: 'Chicago Midway', city: 'Chicago', country: 'USA' },
  { iata: 'ATL', name: 'Atlanta Hartsfield-Jackson', city: 'Atlanta', country: 'USA' },
  { iata: 'DFW', name: 'Dallas Fort Worth', city: 'Dallas', country: 'USA' },
  { iata: 'DEN', name: 'Denver International', city: 'Denver', country: 'USA' },
  { iata: 'MIA', name: 'Miami International', city: 'Miami', country: 'USA' },
  { iata: 'SEA', name: 'Seattle Tacoma', city: 'Seattle', country: 'USA' },
  { iata: 'LAS', name: 'Las Vegas McCarran', city: 'Las Vegas', country: 'USA' },
  { iata: 'PHX', name: 'Phoenix Sky Harbor', city: 'Phoenix', country: 'USA' },
  { iata: 'IAH', name: 'Houston George Bush', city: 'Houston', country: 'USA' },
  { iata: 'BOS', name: 'Boston Logan', city: 'Boston', country: 'USA' },
  { iata: 'PHL', name: 'Philadelphia International', city: 'Philadelphia', country: 'USA' },
  { iata: 'IAD', name: 'Washington Dulles', city: 'Washington', country: 'USA' },
  { iata: 'DCA', name: 'Washington Reagan', city: 'Washington', country: 'USA' },
  { iata: 'MCO', name: 'Orlando International', city: 'Orlando', country: 'USA' },
  { iata: 'FLL', name: 'Fort Lauderdale', city: 'Fort Lauderdale', country: 'USA' },
  { iata: 'MSP', name: 'Minneapolis Saint Paul', city: 'Minneapolis', country: 'USA' },
  { iata: 'DTW', name: 'Detroit Metro', city: 'Detroit', country: 'USA' },
  { iata: 'SLC', name: 'Salt Lake City', city: 'Salt Lake City', country: 'USA' },
  { iata: 'SAN', name: 'San Diego International', city: 'San Diego', country: 'USA' },
  { iata: 'PDX', name: 'Portland International', city: 'Portland', country: 'USA' },
  { iata: 'STL', name: 'St. Louis Lambert', city: 'St. Louis', country: 'USA' },
  { iata: 'TPA', name: 'Tampa International', city: 'Tampa', country: 'USA' },
  { iata: 'BWI', name: 'Baltimore Washington', city: 'Baltimore', country: 'USA' },
  { iata: 'AUS', name: 'Austin Bergstrom', city: 'Austin', country: 'USA' },
  { iata: 'CLT', name: 'Charlotte Douglas', city: 'Charlotte', country: 'USA' },
  { iata: 'MEM', name: 'Memphis International', city: 'Memphis', country: 'USA' },
  { iata: 'BNA', name: 'Nashville International', city: 'Nashville', country: 'USA' },
  { iata: 'RDU', name: 'Raleigh Durham', city: 'Raleigh', country: 'USA' },
  { iata: 'JAX', name: 'Jacksonville International', city: 'Jacksonville', country: 'USA' },
  { iata: 'MSY', name: 'New Orleans Louis Armstrong', city: 'New Orleans', country: 'USA' },
  { iata: 'MCI', name: 'Kansas City International', city: 'Kansas City', country: 'USA' },
  { iata: 'IND', name: 'Indianapolis International', city: 'Indianapolis', country: 'USA' },
  { iata: 'SJC', name: 'San Jose International', city: 'San Jose', country: 'USA' },
  { iata: 'OAK', name: 'Oakland International', city: 'Oakland', country: 'USA' },
  { iata: 'SMF', name: 'Sacramento International', city: 'Sacramento', country: 'USA' },
  { iata: 'ANC', name: 'Anchorage Ted Stevens', city: 'Anchorage', country: 'USA' },
  { iata: 'HNL', name: 'Honolulu Daniel K. Inouye', city: 'Honolulu', country: 'USA' },
  { iata: 'OGG', name: 'Kahului Airport', city: 'Kahului', country: 'USA' },
  { iata: 'KOA', name: 'Kona International', city: 'Kona', country: 'USA' },
  { iata: 'CLE', name: 'Cleveland Hopkins', city: 'Cleveland', country: 'USA' },
  { iata: 'PIT', name: 'Pittsburgh International', city: 'Pittsburgh', country: 'USA' },
  { iata: 'CVG', name: 'Cincinnati Northern Kentucky', city: 'Cincinnati', country: 'USA' },
  { iata: 'MKE', name: 'Milwaukee Mitchell', city: 'Milwaukee', country: 'USA' },
  { iata: 'CMH', name: 'Columbus International', city: 'Columbus', country: 'USA' },
  { iata: 'ABQ', name: 'Albuquerque International', city: 'Albuquerque', country: 'USA' },
  { iata: 'BOI', name: 'Boise Airport', city: 'Boise', country: 'USA' },
  { iata: 'BUR', name: 'Burbank Bob Hope', city: 'Burbank', country: 'USA' },
  { iata: 'SNA', name: 'Santa Ana John Wayne', city: 'Santa Ana', country: 'USA' },
  { iata: 'ONT', name: 'Ontario International', city: 'Ontario', country: 'USA' },
  { iata: 'RNO', name: 'Reno Tahoe', city: 'Reno', country: 'USA' },
  { iata: 'TUS', name: 'Tucson International', city: 'Tucson', country: 'USA' },
  { iata: 'OKC', name: 'Oklahoma City Will Rogers', city: 'Oklahoma City', country: 'USA' },
  { iata: 'TUL', name: 'Tulsa International', city: 'Tulsa', country: 'USA' },
  { iata: 'BUF', name: 'Buffalo Niagara', city: 'Buffalo', country: 'USA' },
  { iata: 'RIC', name: 'Richmond International', city: 'Richmond', country: 'USA' },
  { iata: 'ORF', name: 'Norfolk International', city: 'Norfolk', country: 'USA' },
  { iata: 'SAT', name: 'San Antonio International', city: 'San Antonio', country: 'USA' },
  { iata: 'ELP', name: 'El Paso International', city: 'El Paso', country: 'USA' },
  { iata: 'BHM', name: 'Birmingham Shuttlesworth', city: 'Birmingham', country: 'USA' },
  { iata: 'DSM', name: 'Des Moines International', city: 'Des Moines', country: 'USA' },
  { iata: 'OMA', name: 'Omaha Eppley', city: 'Omaha', country: 'USA' },
  { iata: 'ICT', name: 'Wichita Dwight D. Eisenhower', city: 'Wichita', country: 'USA' },
  { iata: 'GRR', name: 'Grand Rapids Gerald R. Ford', city: 'Grand Rapids', country: 'USA' },
  { iata: 'BDL', name: 'Hartford Bradley', city: 'Hartford', country: 'USA' },
  { iata: 'PVD', name: 'Providence T. F. Green', city: 'Providence', country: 'USA' },
  { iata: 'MHT', name: 'Manchester Boston Regional', city: 'Manchester', country: 'USA' },
  { iata: 'PWM', name: 'Portland International Jetport', city: 'Portland', country: 'USA' },
  { iata: 'BZN', name: 'Bozeman Yellowstone', city: 'Bozeman', country: 'USA' },
  { iata: 'JAC', name: 'Jackson Hole Airport', city: 'Jackson', country: 'USA' },
  { iata: 'BIL', name: 'Billings Logan', city: 'Billings', country: 'USA' },
  { iata: 'FAR', name: 'Fargo Hector', city: 'Fargo', country: 'USA' },
  { iata: 'RAP', name: 'Rapid City Regional', city: 'Rapid City', country: 'USA' },
  { iata: 'GEG', name: 'Spokane International', city: 'Spokane', country: 'USA' },
  { iata: 'MSO', name: 'Missoula Airport', city: 'Missoula', country: 'USA' },
  { iata: 'EUG', name: 'Eugene Mahlon Sweet', city: 'Eugene', country: 'USA' },
  { iata: 'HPN', name: 'White Plains Westchester', city: 'White Plains', country: 'USA' },
  { iata: 'ISP', name: 'Long Island MacArthur', city: 'Islip', country: 'USA' },
  { iata: 'ACY', name: 'Atlantic City International', city: 'Atlantic City', country: 'USA' },
  { iata: 'ABE', name: 'Allentown Lehigh Valley', city: 'Allentown', country: 'USA' },
  { iata: 'AVL', name: 'Asheville Regional', city: 'Asheville', country: 'USA' },
  { iata: 'CHS', name: 'Charleston International', city: 'Charleston', country: 'USA' },
  { iata: 'SAV', name: 'Savannah Hilton Head', city: 'Savannah', country: 'USA' },
  { iata: 'CAE', name: 'Columbia Metropolitan', city: 'Columbia', country: 'USA' },
  { iata: 'PNS', name: 'Pensacola International', city: 'Pensacola', country: 'USA' },
  { iata: 'VPS', name: 'Valparaiso Eglin', city: 'Valparaiso', country: 'USA' },
  { iata: 'ECP', name: 'Panama City Beaches', city: 'Panama City', country: 'USA' },
  { iata: 'GNV', name: 'Gainesville Regional', city: 'Gainesville', country: 'USA' },
  { iata: 'TYS', name: 'Knoxville McGhee Tyson', city: 'Knoxville', country: 'USA' },
  { iata: 'CHA', name: 'Chattanooga Lovell Field', city: 'Chattanooga', country: 'USA' },
  { iata: 'HSV', name: 'Huntsville International', city: 'Huntsville', country: 'USA' },
  { iata: 'MGW', name: 'Morgantown Municipal', city: 'Morgantown', country: 'USA' },
  { iata: 'CRW', name: 'Charleston Yeager', city: 'Charleston', country: 'USA' },
  { iata: 'HTS', name: 'Huntington Tri-State', city: 'Huntington', country: 'USA' },
  { iata: 'SYR', name: 'Syracuse Hancock', city: 'Syracuse', country: 'USA' },
  { iata: 'ALB', name: 'Albany International', city: 'Albany', country: 'USA' },
  { iata: 'ROC', name: 'Rochester International', city: 'Rochester', country: 'USA' },
  // Kanada
  { iata: 'YYZ', name: 'Toronto Pearson', city: 'Toronto', country: 'Kanada' },
  { iata: 'YVR', name: 'Vancouver International', city: 'Vancouver', country: 'Kanada' },
  { iata: 'YUL', name: 'Montréal Trudeau', city: 'Montréal', country: 'Kanada' },
  { iata: 'YYC', name: 'Calgary International', city: 'Calgary', country: 'Kanada' },
  { iata: 'YEG', name: 'Edmonton International', city: 'Edmonton', country: 'Kanada' },
  { iata: 'YOW', name: 'Ottawa Macdonald-Cartier', city: 'Ottawa', country: 'Kanada' },
  { iata: 'YHZ', name: 'Halifax Stanfield', city: 'Halifax', country: 'Kanada' },
  { iata: 'YWG', name: 'Winnipeg Richardson', city: 'Winnipeg', country: 'Kanada' },
  { iata: 'YQB', name: 'Québec Jean Lesage', city: 'Québec', country: 'Kanada' },
  { iata: 'YQR', name: 'Regina International', city: 'Regina', country: 'Kanada' },
  { iata: 'YXE', name: 'Saskatoon Diefenbaker', city: 'Saskatoon', country: 'Kanada' },
  { iata: 'YYJ', name: 'Victoria International', city: 'Victoria', country: 'Kanada' },
  { iata: 'YYT', name: 'St. John\'s International', city: 'St. John\'s', country: 'Kanada' },
  { iata: 'YKA', name: 'Kamloops Airport', city: 'Kamloops', country: 'Kanada' },
  { iata: 'YXY', name: 'Whitehorse Erik Nielsen', city: 'Whitehorse', country: 'Kanada' },
  { iata: 'YZF', name: 'Yellowknife Airport', city: 'Yellowknife', country: 'Kanada' },
  { iata: 'YFC', name: 'Fredericton Airport', city: 'Fredericton', country: 'Kanada' },
  { iata: 'YYG', name: 'Charlottetown Airport', city: 'Charlottetown', country: 'Kanada' },
  { iata: 'YQT', name: 'Thunder Bay Airport', city: 'Thunder Bay', country: 'Kanada' },
  // Mexiko
  { iata: 'MEX', name: 'Mexico City International', city: 'Mexiko-Stadt', country: 'Mexiko' },
  { iata: 'CUN', name: 'Cancún International', city: 'Cancún', country: 'Mexiko' },
  { iata: 'GDL', name: 'Guadalajara International', city: 'Guadalajara', country: 'Mexiko' },
  { iata: 'MTY', name: 'Monterrey International', city: 'Monterrey', country: 'Mexiko' },
  { iata: 'PVR', name: 'Puerto Vallarta', city: 'Puerto Vallarta', country: 'Mexiko' },
  { iata: 'SJD', name: 'Los Cabos International', city: 'Los Cabos', country: 'Mexiko' },
  { iata: 'MID', name: 'Mérida International', city: 'Mérida', country: 'Mexiko' },
  { iata: 'TIJ', name: 'Tijuana International', city: 'Tijuana', country: 'Mexiko' },
  { iata: 'BJX', name: 'León Guanajuato', city: 'León', country: 'Mexiko' },
  { iata: 'CUL', name: 'Culiacán International', city: 'Culiacán', country: 'Mexiko' },
  { iata: 'HUX', name: 'Huatulco International', city: 'Huatulco', country: 'Mexiko' },
  { iata: 'ZIH', name: 'Ixtapa Zihuatanejo', city: 'Ixtapa', country: 'Mexiko' },
  { iata: 'OAX', name: 'Oaxaca International', city: 'Oaxaca', country: 'Mexiko' },
  { iata: 'VER', name: 'Veracruz International', city: 'Veracruz', country: 'Mexiko' },
  { iata: 'CJS', name: 'Ciudad Juárez', city: 'Ciudad Juárez', country: 'Mexiko' },
  { iata: 'CZM', name: 'Cozumel International', city: 'Cozumel', country: 'Mexiko' },
  { iata: 'LAP', name: 'La Paz International', city: 'La Paz', country: 'Mexiko' },
  { iata: 'MZT', name: 'Mazatlán International', city: 'Mazatlán', country: 'Mexiko' },
  { iata: 'HMO', name: 'Hermosillo International', city: 'Hermosillo', country: 'Mexiko' },
  { iata: 'TGZ', name: 'Tuxtla Gutiérrez', city: 'Tuxtla Gutiérrez', country: 'Mexiko' },
  { iata: 'CTM', name: 'Chetumal International', city: 'Chetumal', country: 'Mexiko' },
  // Mittelamerika
  { iata: 'GUA', name: 'Guatemala City La Aurora', city: 'Guatemala-Stadt', country: 'Guatemala' },
  { iata: 'FRS', name: 'Flores Mundo Maya', city: 'Flores', country: 'Guatemala' },
  { iata: 'SAL', name: 'San Salvador Monseñor Romero', city: 'San Salvador', country: 'El Salvador' },
  { iata: 'SAP', name: 'San Pedro Sula Ramón Villeda', city: 'San Pedro Sula', country: 'Honduras' },
  { iata: 'TGU', name: 'Tegucigalpa Toncontín', city: 'Tegucigalpa', country: 'Honduras' },
  { iata: 'RTB', name: 'Roatán International', city: 'Roatán', country: 'Honduras' },
  { iata: 'MGA', name: 'Managua Augusto Sandino', city: 'Managua', country: 'Nicaragua' },
  { iata: 'SJO', name: 'San José Juan Santamaría', city: 'San José', country: 'Costa Rica' },
  { iata: 'LIR', name: 'Liberia Daniel Oduber', city: 'Liberia', country: 'Costa Rica' },
  { iata: 'PTY', name: 'Panama-Stadt Tocumen', city: 'Panama-Stadt', country: 'Panama' },
  { iata: 'PAC', name: 'Panama Pacifico', city: 'Panama-Stadt', country: 'Panama' },
  { iata: 'DAV', name: 'David Enrique Malek', city: 'David', country: 'Panama' },
  { iata: 'BZE', name: 'Belize International', city: 'Belize-Stadt', country: 'Belize' },
  // Karibik
  { iata: 'HAV', name: 'Havanna José Martí', city: 'Havanna', country: 'Kuba' },
  { iata: 'VRA', name: 'Varadero Juan Gualberto Gómez', city: 'Varadero', country: 'Kuba' },
  { iata: 'SDQ', name: 'Santo Domingo Las Américas', city: 'Santo Domingo', country: 'Dominikanische Republik' },
  { iata: 'PUJ', name: 'Punta Cana International', city: 'Punta Cana', country: 'Dominikanische Republik' },
  { iata: 'STI', name: 'Santiago Cibao', city: 'Santiago', country: 'Dominikanische Republik' },
  { iata: 'SJU', name: 'San Juan Luis Muñoz Marín', city: 'San Juan', country: 'Puerto Rico' },
  { iata: 'KIN', name: 'Kingston Norman Manley', city: 'Kingston', country: 'Jamaika' },
  { iata: 'MBJ', name: 'Montego Bay Sangster', city: 'Montego Bay', country: 'Jamaika' },
  { iata: 'NAS', name: 'Nassau Lynden Pindling', city: 'Nassau', country: 'Bahamas' },
  { iata: 'FPO', name: 'Freeport Grand Bahama', city: 'Freeport', country: 'Bahamas' },
  { iata: 'BGI', name: 'Barbados Grantley Adams', city: 'Bridgetown', country: 'Barbados' },
  { iata: 'POS', name: 'Port of Spain Piarco', city: 'Port of Spain', country: 'Trinidad und Tobago' },
  { iata: 'PAP', name: 'Port-au-Prince', city: 'Port-au-Prince', country: 'Haiti' },
  { iata: 'CUR', name: 'Curaçao Hato', city: 'Willemstad', country: 'Curaçao' },
  { iata: 'AUA', name: 'Aruba Queen Beatrix', city: 'Oranjestad', country: 'Aruba' },
  { iata: 'SXM', name: 'Sint Maarten Princess Juliana', city: 'Philipsburg', country: 'Sint Maarten' },
  { iata: 'BON', name: 'Bonaire Flamingo', city: 'Kralendijk', country: 'Bonaire' },
  { iata: 'GCM', name: 'Grand Cayman', city: 'George Town', country: 'Kaimaninseln' },
  // Südamerika
  { iata: 'SAO', name: 'São Paulo Guarulhos', city: 'São Paulo', country: 'Brasilien' },
  { iata: 'GRU', name: 'São Paulo Guarulhos', city: 'São Paulo', country: 'Brasilien' },
  { iata: 'CGH', name: 'São Paulo Congonhas', city: 'São Paulo', country: 'Brasilien' },
  { iata: 'VCP', name: 'Viracopos Campinas', city: 'Campinas', country: 'Brasilien' },
  { iata: 'GIG', name: 'Rio de Janeiro Galeão', city: 'Rio de Janeiro', country: 'Brasilien' },
  { iata: 'SDU', name: 'Santos Dumont', city: 'Rio de Janeiro', country: 'Brasilien' },
  { iata: 'BSB', name: 'Brasília International', city: 'Brasília', country: 'Brasilien' },
  { iata: 'CNF', name: 'Belo Horizonte Confins', city: 'Belo Horizonte', country: 'Brasilien' },
  { iata: 'SSA', name: 'Salvador Luís E. Magalhães', city: 'Salvador', country: 'Brasilien' },
  { iata: 'REC', name: 'Recife Guararapes', city: 'Recife', country: 'Brasilien' },
  { iata: 'FOR', name: 'Fortaleza Pinto Martins', city: 'Fortaleza', country: 'Brasilien' },
  { iata: 'POA', name: 'Porto Alegre Salgado Filho', city: 'Porto Alegre', country: 'Brasilien' },
  { iata: 'CWB', name: 'Curitiba Afonso Pena', city: 'Curitiba', country: 'Brasilien' },
  { iata: 'MAO', name: 'Manaus Eduardo Gomes', city: 'Manaus', country: 'Brasilien' },
  { iata: 'BEL', name: 'Belém Val de Cans', city: 'Belém', country: 'Brasilien' },
  { iata: 'FLN', name: 'Florianópolis Hercílio Luz', city: 'Florianópolis', country: 'Brasilien' },
  { iata: 'NAT', name: 'Natal São Gonçalo', city: 'Natal', country: 'Brasilien' },
  { iata: 'MCZ', name: 'Maceió Zumbi dos Palmares', city: 'Maceió', country: 'Brasilien' },
  { iata: 'VIX', name: 'Vitória Goiabeiras', city: 'Vitória', country: 'Brasilien' },
  { iata: 'EZE', name: 'Buenos Aires Ezeiza', city: 'Buenos Aires', country: 'Argentinien' },
  { iata: 'AEP', name: 'Buenos Aires Aeroparque', city: 'Buenos Aires', country: 'Argentinien' },
  { iata: 'COR', name: 'Córdoba Pajas Blancas', city: 'Córdoba', country: 'Argentinien' },
  { iata: 'MDZ', name: 'Mendoza El Plumerillo', city: 'Mendoza', country: 'Argentinien' },
  { iata: 'BRC', name: 'Bariloche International', city: 'Bariloche', country: 'Argentinien' },
  { iata: 'USH', name: 'Ushuaia Malvinas Argentinas', city: 'Ushuaia', country: 'Argentinien' },
  { iata: 'IGR', name: 'Iguazú Cataratas', city: 'Iguazú', country: 'Argentinien' },
  { iata: 'SCL', name: 'Santiago International', city: 'Santiago', country: 'Chile' },
  { iata: 'IPC', name: 'Osterinsel Mataveri', city: 'Osterinsel', country: 'Chile' },
  { iata: 'ANF', name: 'Antofagasta Cerro Moreno', city: 'Antofagasta', country: 'Chile' },
  { iata: 'CJC', name: 'Calama El Loa', city: 'Calama', country: 'Chile' },
  { iata: 'PMC', name: 'Puerto Montt El Tepual', city: 'Puerto Montt', country: 'Chile' },
  { iata: 'CCP', name: 'Concepción Carriel Sur', city: 'Concepción', country: 'Chile' },
  { iata: 'ZAL', name: 'Valdivia Pichoy', city: 'Valdivia', country: 'Chile' },
  { iata: 'PUQ', name: 'Punta Arenas Carlos Ibáñez', city: 'Punta Arenas', country: 'Chile' },
  { iata: 'BOG', name: 'Bogotá El Dorado', city: 'Bogotá', country: 'Kolumbien' },
  { iata: 'MDE', name: 'Medellín José María Córdova', city: 'Medellín', country: 'Kolumbien' },
  { iata: 'CLO', name: 'Cali Alfonso Bonilla Aragón', city: 'Cali', country: 'Kolumbien' },
  { iata: 'CTG', name: 'Cartagena Rafael Núñez', city: 'Cartagena', country: 'Kolumbien' },
  { iata: 'BAQ', name: 'Barranquilla Ernesto Cortissoz', city: 'Barranquilla', country: 'Kolumbien' },
  { iata: 'SMR', name: 'Santa Marta Simón Bolívar', city: 'Santa Marta', country: 'Kolumbien' },
  { iata: 'PEI', name: 'Pereira Matecaña', city: 'Pereira', country: 'Kolumbien' },
  { iata: 'BGA', name: 'Bucaramanga Palonegro', city: 'Bucaramanga', country: 'Kolumbien' },
  { iata: 'CUC', name: 'Cúcuta Camilo Daza', city: 'Cúcuta', country: 'Kolumbien' },
  { iata: 'LET', name: 'Leticia Alfredo Vasquez Cobo', city: 'Leticia', country: 'Kolumbien' },
  { iata: 'LIM', name: 'Lima Jorge Chávez', city: 'Lima', country: 'Peru' },
  { iata: 'CUZ', name: 'Cusco Alejandro Velasco Astete', city: 'Cusco', country: 'Peru' },
  { iata: 'AQP', name: 'Arequipa Rodríguez Ballón', city: 'Arequipa', country: 'Peru' },
  { iata: 'IQT', name: 'Iquitos Coronel FAP', city: 'Iquitos', country: 'Peru' },
  { iata: 'TRU', name: 'Trujillo Capitán FAP', city: 'Trujillo', country: 'Peru' },
  { iata: 'PIU', name: 'Piura FAP Guillermo', city: 'Piura', country: 'Peru' },
  { iata: 'CIX', name: 'Chiclayo FAP José Quiñones', city: 'Chiclayo', country: 'Peru' },
  { iata: 'UIO', name: 'Quito Mariscal Sucre', city: 'Quito', country: 'Ecuador' },
  { iata: 'GYE', name: 'Guayaquil José Joaquín de Olmedo', city: 'Guayaquil', country: 'Ecuador' },
  { iata: 'CUE', name: 'Cuenca Mariscal La Mar', city: 'Cuenca', country: 'Ecuador' },
  { iata: 'GPS', name: 'Galápagos Seymour', city: 'Galápagos', country: 'Ecuador' },
  { iata: 'LPB', name: 'La Paz El Alto', city: 'La Paz', country: 'Bolivien' },
  { iata: 'CBB', name: 'Cochabamba Jorge Wilstermann', city: 'Cochabamba', country: 'Bolivien' },
  { iata: 'VVI', name: 'Santa Cruz Viru Viru', city: 'Santa Cruz', country: 'Bolivien' },
  { iata: 'SRE', name: 'Sucre Juana Azurduy', city: 'Sucre', country: 'Bolivien' },
  { iata: 'TJA', name: 'Tarija Capitán Oriel Lea', city: 'Tarija', country: 'Bolivien' },
  { iata: 'ASU', name: 'Asunción Silvio Pettirossi', city: 'Asunción', country: 'Paraguay' },
  { iata: 'MVD', name: 'Montevideo Carrasco', city: 'Montevideo', country: 'Uruguay' },
  { iata: 'PDP', name: 'Punta del Este', city: 'Punta del Este', country: 'Uruguay' },
  { iata: 'CCS', name: 'Caracas Simón Bolívar', city: 'Caracas', country: 'Venezuela' },
  { iata: 'MAR', name: 'Maracaibo La Chinita', city: 'Maracaibo', country: 'Venezuela' },
  { iata: 'VLN', name: 'Valencia Arturo Michelena', city: 'Valencia', country: 'Venezuela' },
  { iata: 'GEO', name: 'Georgetown Cheddi Jagan', city: 'Georgetown', country: 'Guyana' },
  { iata: 'PBM', name: 'Paramaribo Johan Adolf Pengel', city: 'Paramaribo', country: 'Suriname' },
  { iata: 'CAY', name: 'Cayenne Félix Eboué', city: 'Cayenne', country: 'Französisch-Guayana' },
  // Ozeanien - Australien
  { iata: 'SYD', name: 'Sydney Kingsford Smith', city: 'Sydney', country: 'Australien' },
  { iata: 'MEL', name: 'Melbourne Tullamarine', city: 'Melbourne', country: 'Australien' },
  { iata: 'BNE', name: 'Brisbane Airport', city: 'Brisbane', country: 'Australien' },
  { iata: 'PER', name: 'Perth Airport', city: 'Perth', country: 'Australien' },
  { iata: 'ADL', name: 'Adelaide Airport', city: 'Adelaide', country: 'Australien' },
  { iata: 'OOL', name: 'Gold Coast Airport', city: 'Gold Coast', country: 'Australien' },
  { iata: 'CNS', name: 'Cairns Airport', city: 'Cairns', country: 'Australien' },
  { iata: 'HBA', name: 'Hobart Airport', city: 'Hobart', country: 'Australien' },
  { iata: 'CBR', name: 'Canberra Airport', city: 'Canberra', country: 'Australien' },
  { iata: 'DRW', name: 'Darwin Airport', city: 'Darwin', country: 'Australien' },
  { iata: 'ASP', name: 'Alice Springs', city: 'Alice Springs', country: 'Australien' },
  { iata: 'TSV', name: 'Townsville Airport', city: 'Townsville', country: 'Australien' },
  { iata: 'MCY', name: 'Sunshine Coast', city: 'Maroochydore', country: 'Australien' },
  { iata: 'NTL', name: 'Newcastle Airport', city: 'Newcastle', country: 'Australien' },
  { iata: 'AYQ', name: 'Ayers Rock Connellan', city: 'Yulara', country: 'Australien' },
  { iata: 'AVV', name: 'Avalon Airport', city: 'Avalon', country: 'Australien' },
  { iata: 'LST', name: 'Launceston Airport', city: 'Launceston', country: 'Australien' },
  { iata: 'MKY', name: 'Mackay Airport', city: 'Mackay', country: 'Australien' },
  { iata: 'ROK', name: 'Rockhampton Airport', city: 'Rockhampton', country: 'Australien' },
  // Neuseeland
  { iata: 'AKL', name: 'Auckland International', city: 'Auckland', country: 'Neuseeland' },
  { iata: 'WLG', name: 'Wellington Airport', city: 'Wellington', country: 'Neuseeland' },
  { iata: 'CHC', name: 'Christchurch Airport', city: 'Christchurch', country: 'Neuseeland' },
  { iata: 'ZQN', name: 'Queenstown Airport', city: 'Queenstown', country: 'Neuseeland' },
  { iata: 'DUD', name: 'Dunedin Airport', city: 'Dunedin', country: 'Neuseeland' },
  { iata: 'NPE', name: 'Napier Hawke\'s Bay', city: 'Napier', country: 'Neuseeland' },
  { iata: 'ROT', name: 'Rotorua Airport', city: 'Rotorua', country: 'Neuseeland' },
  { iata: 'IVC', name: 'Invercargill Airport', city: 'Invercargill', country: 'Neuseeland' },
  { iata: 'NSN', name: 'Nelson Airport', city: 'Nelson', country: 'Neuseeland' },
  { iata: 'HLZ', name: 'Hamilton Airport', city: 'Hamilton', country: 'Neuseeland' },
  { iata: 'PMR', name: 'Palmerston North', city: 'Palmerston North', country: 'Neuseeland' },
  { iata: 'TRG', name: 'Tauranga Airport', city: 'Tauranga', country: 'Neuseeland' },
  // Pazifik-Inseln
  { iata: 'NAN', name: 'Nadi International', city: 'Nadi', country: 'Fidschi' },
  { iata: 'SUV', name: 'Suva Nausori', city: 'Suva', country: 'Fidschi' },
  { iata: 'APW', name: 'Apia Faleolo', city: 'Apia', country: 'Samoa' },
  { iata: 'TBU', name: 'Nuku\'alofa Fua\'amotu', city: 'Nuku\'alofa', country: 'Tonga' },
  { iata: 'VLI', name: 'Port Vila Bauerfield', city: 'Port Vila', country: 'Vanuatu' },
  { iata: 'HIR', name: 'Honiara Henderson', city: 'Honiara', country: 'Salomonen' },
  { iata: 'POM', name: 'Port Moresby Jacksons', city: 'Port Moresby', country: 'Papua-Neuguinea' },
  { iata: 'NOU', name: 'Nouméa La Tontouta', city: 'Nouméa', country: 'Neukaledonien' },
  { iata: 'PPT', name: 'Papeete Faaa', city: 'Papeete', country: 'Französisch-Polynesien' },
  { iata: 'GUM', name: 'Guam Antonio B. Won Pat', city: 'Hagåtña', country: 'Guam' },
  { iata: 'SPN', name: 'Saipan International', city: 'Saipan', country: 'Nördliche Marianen' },
  { iata: 'PPG', name: 'Pago Pago International', city: 'Pago Pago', country: 'Amerikanisch-Samoa' },
  { iata: 'IUE', name: 'Niue International', city: 'Alofi', country: 'Niue' },
  { iata: 'WLS', name: 'Wallis Hihifo', city: 'Wallis', country: 'Wallis und Futuna' },
  { iata: 'FGU', name: 'Futuna Island', city: 'Futuna', country: 'Wallis und Futuna' },
];

const AIRPORT_IATA_MAP: Map<string, Airport> = new Map();
for (const a of AIRPORTS) {
  AIRPORT_IATA_MAP.set(a.iata.toLowerCase(), a);
}

export function findAirportByIata(iata: string): Airport | null {
  return AIRPORT_IATA_MAP.get(iata.trim().toLowerCase()) ?? null;
}

export function searchAirports(query: string): Airport[] {
  if (!query.trim()) return AIRPORTS.slice(0, 30);
  const q = query.toLowerCase().trim();
  return AIRPORTS.filter(
    (a) =>
      a.iata.toLowerCase().includes(q) ||
      a.name.toLowerCase().includes(q) ||
      a.city.toLowerCase().includes(q) ||
      a.country.toLowerCase().includes(q)
  ).slice(0, 30);
}
